### ISSUE TITLE
Is the project live?

### ISSUE THREAD

**Issue by ABSanthosh** [AleksandraRolka/RelativityxAGH-Azure-project#1]
Hi! 
I tried to open this project through this [website](https://vocabulary-boost-up.azurewebsites.net/) but it says 403: webapp stopped. I don't think I can run this locally so let me know if you ever plan to make it live again.

By the way, I came across this project since you are using one of my libraries `react-quizlet-flashcard` and I'm very happy to see my library being used. I hope you had no friction while using my library!!

**Comment by AleksandraRolka** [comment]
Hi @ABSanthosh! ✋ 
Yes, the app is not running anymore, because it was made as a university project under university subscription credits. 
If you would like to run it you have to make backend on your own unfortunately, you could use code of my serverless backend and deploy it on Azure, I used Azure Functions and CosmosDB services. But you need to of course change a little bit, for example, DB connection details. 
And depends on where you want to run frontend, if you want to deploy it on Azure as a WebApp service or run it locally, you need to change _baseURL_  value in [vocabulary-boost-up-app/src/config.js](https://github.com/AleksandraRolka/RelativityxAGH-Azure-project/blob/main/vocabulary-boost-up-app/src/config.js)

And yes! It was fun and easy to work with your library 😃 I'm grateful for your work, nice interface and UI 😃 👏

**Comment by ABSanthosh** [comment]
Hey @AleksandraRolka!
Its unfortunate that I can't try the live site but I will definitely try to set it up when I get time! I'm glad you had fun using my library! 😄 

Have a good one!
